"""Incremental graph update logic.

Detects changed files via git diff, re-parses only changed + impacted files,
and updates the graph accordingly.
"""

from __future__ import annotations

import fnmatch
import hashlib
import logging
import shutil
import subprocess
import threading
import time
from pathlib import Path
from typing import TYPE_CHECKING, Any

from watchdog.events import FileSystemEventHandler
from watchdog.observers import Observer

from .graph import GraphStore
from .parser import CodeParser

if TYPE_CHECKING:
    from .federation import RepoRegistry

logger = logging.getLogger(__name__)

# Default ignore patterns (in addition to .gitignore)
DEFAULT_IGNORE_PATTERNS = [
    ".code-review-graph/**",
    "node_modules/**",
    ".git/**",
    "__pycache__/**",
    "*.pyc",
    ".venv/**",
    "venv/**",
    "dist/**",
    "build/**",
    ".next/**",
    "target/**",
    "*.min.js",
    "*.min.css",
    "*.map",
    "*.lock",
    "package-lock.json",
    "yarn.lock",
    "*.db",
    "*.sqlite",
    "*.db-journal",
    "*.db-wal",
]


def find_repo_root(start: Path | None = None) -> Path | None:
    """Walk up from start to find the nearest .git directory."""
    current = start or Path.cwd()
    while current != current.parent:
        if (current / ".git").exists():
            return current
        current = current.parent
    if (current / ".git").exists():
        return current
    return None


def find_project_root(start: Path | None = None) -> Path:
    """Find the project root: git repo root if available, otherwise cwd."""
    root = find_repo_root(start)
    if root:
        return root
    return start or Path.cwd()


def get_db_path(repo_root: Path) -> Path:
    """Determine the database path for a repository.

    HTTP multi-user remote mode (a JWT ``sub`` is bound to the current
    request by the ``auth_scope`` middleware): the graph DB is scoped to
    that sub at ``<CRG_DATA_DIR>/subs/<sub>/graph.db`` so one user's
    code-graph nodes/edges/summaries never reach another concurrent user
    sharing the same deployment. ``repo_root`` is ignored in this mode --
    the analyzed-repo directory is not a safe shared location for a
    per-tenant database.

    Stdio / single-user HTTP (no sub bound): the database lives inside the
    analyzed repository at ``<repo_root>/.code-review-graph/graph.db``.
    Creates the ``.code-review-graph/`` directory and an inner ``.gitignore``
    (with ``*``) so generated files are never committed.  If a legacy
    ``.code-review-graph.db`` exists at the repo root the database is migrated
    into the new directory (WAL/SHM side-files are discarded).

    Imported lazily to keep the module-load import graph (and the stdio
    hot path) untouched; the per-sub value flows request-scoped and is
    never written to the process-global environment.
    """
    from .credential_state import db_path_for_sub, get_current_sub

    sub = get_current_sub()
    if sub is not None:
        return db_path_for_sub(sub)

    crg_dir = repo_root / ".code-review-graph"
    new_db = crg_dir / "graph.db"

    # Ensure directory exists
    crg_dir.mkdir(exist_ok=True)

    # Auto-create .gitignore inside the directory (idempotent)
    inner_gitignore = crg_dir / ".gitignore"
    if not inner_gitignore.exists():
        inner_gitignore.write_text(
            "# Auto-generated by code-review-graph — do not commit database files.\n"
            "# The graph.db contains absolute paths and code structure metadata.\n"
            "*\n"
        )

    # Migrate legacy database if present
    legacy_db = repo_root / ".code-review-graph.db"
    if legacy_db.exists() and not new_db.exists():
        legacy_db.rename(new_db)
    # Discard stale WAL/SHM side-files from the old location
    for suffix in ("-wal", "-shm", "-journal"):
        side = repo_root / f".code-review-graph.db{suffix}"
        if side.exists():
            side.unlink()

    return new_db


def _load_ignore_patterns(repo_root: Path) -> list[str]:
    """Load ignore patterns from .code-review-graphignore file."""
    patterns = list(DEFAULT_IGNORE_PATTERNS)
    ignore_file = repo_root / ".code-review-graphignore"
    if ignore_file.exists():
        for line in ignore_file.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                patterns.append(line)
    return patterns


def _should_ignore(path: str, patterns: list[str]) -> bool:
    """Check if a path matches any ignore pattern."""
    return any(fnmatch.fnmatch(path, p) for p in patterns)


def _is_binary(path: Path) -> bool:
    """Quick heuristic: check if file appears to be binary."""
    try:
        chunk = path.read_bytes()[:8192]
        return b"\x00" in chunk
    except (OSError, PermissionError):
        return True


_GIT_TIMEOUT = 30  # seconds

# Every git subprocess below passes ``stdin=subprocess.DEVNULL``.
#
# The git child must not inherit the parent's stdin handle. When the MCP server
# runs over stdio, its own stdin is a pipe from the client, and FastMCP executes
# each sync tool in an anyio worker thread (under the asyncio Proactor loop). On
# Windows, a git child that inherits that stdin pipe keeps subprocess's
# output-reader thread (``_communicate`` -> ``_readerthread``) from ever seeing
# EOF, so ``communicate()`` blocks until ``_GIT_TIMEOUT`` -- turning an instant
# ``git ls-files``/``git status`` into a 30 s stall per call (a full build that
# makes several git calls then takes a minute+). Detaching stdin breaks the
# inheritance and the reads return immediately.


def _run_git(
    repo_root: Path, args: list[str]
) -> subprocess.CompletedProcess[str] | None:
    """Run a git command and return the completed process, or None if unavailable."""
    git_bin = shutil.which("git")
    if not git_bin:
        return None
    try:
        return subprocess.run(
            [git_bin, *args],
            capture_output=True,
            text=True,
            cwd=str(repo_root),
            timeout=_GIT_TIMEOUT,
            stdin=subprocess.DEVNULL,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None


def get_head_sha(repo_root: Path) -> str | None:
    """Return current HEAD commit SHA, or None if git/HEAD unavailable."""
    result = _run_git(repo_root, ["rev-parse", "HEAD"])
    if result is None or result.returncode != 0:
        return None
    sha = result.stdout.strip()
    return sha or None


def is_valid_commit(repo_root: Path, sha: str) -> bool:
    """Return True if sha identifies a reachable commit object."""
    if not sha:
        return False
    # SECURITY: Prevent argument injection to git cat-file
    if sha.startswith("-"):
        return False
    result = _run_git(repo_root, ["cat-file", "-e", f"{sha}^{{commit}}"])
    return result is not None and result.returncode == 0


def get_changed_files(repo_root: Path, base: str = "HEAD~1") -> list[str]:
    """Get list of changed files via git diff."""
    if base.startswith("-"):
        raise ValueError(f"Invalid git ref: {base}")

    git_bin = shutil.which("git")
    if not git_bin:
        raise RuntimeError("git executable not found")

    try:
        result = subprocess.run(
            [git_bin, "diff", "--name-only", "--end-of-options", base],
            capture_output=True,
            text=True,
            cwd=str(repo_root),
            timeout=_GIT_TIMEOUT,
            stdin=subprocess.DEVNULL,
        )
        if result.returncode != 0:
            # Fallback: try diff against empty tree (initial commit)
            result = subprocess.run(
                [git_bin, "diff", "--name-only", "--cached"],
                capture_output=True,
                text=True,
                cwd=str(repo_root),
                timeout=_GIT_TIMEOUT,
            )
        files = [f.strip() for f in result.stdout.splitlines() if f.strip()]
        return files
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []


def get_staged_and_unstaged(repo_root: Path) -> list[str]:
    """Get all modified files (staged + unstaged + untracked)."""
    git_bin = shutil.which("git")
    if not git_bin:
        raise RuntimeError("git executable not found")

    try:
        result = subprocess.run(
            [git_bin, "status", "--porcelain"],
            capture_output=True,
            text=True,
            cwd=str(repo_root),
            timeout=_GIT_TIMEOUT,
            stdin=subprocess.DEVNULL,
        )
        files = []
        for line in result.stdout.splitlines():
            if len(line) > 3:
                entry = line[3:].strip()
                # Handle renamed files: "R  old -> new"
                if " -> " in entry:
                    entry = entry.split(" -> ", 1)[1]
                files.append(entry)
        return files
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []


def get_all_tracked_files(repo_root: Path) -> list[str]:
    """Get all files tracked by git."""
    git_bin = shutil.which("git")
    if not git_bin:
        raise RuntimeError("git executable not found")

    try:
        result = subprocess.run(
            [git_bin, "ls-files"],
            capture_output=True,
            text=True,
            cwd=str(repo_root),
            timeout=_GIT_TIMEOUT,
            stdin=subprocess.DEVNULL,
        )
        return [f.strip() for f in result.stdout.splitlines() if f.strip()]
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []


def collect_all_files(repo_root: Path) -> list[str]:
    """Collect all parseable files in the repo, respecting ignore patterns."""
    ignore_patterns = _load_ignore_patterns(repo_root)
    parser = CodeParser()
    files = []

    # Prefer git ls-files for tracked files
    tracked = get_all_tracked_files(repo_root)
    if tracked:
        candidates = tracked
    else:
        # Fallback: walk directory
        candidates = [
            str(p.relative_to(repo_root)) for p in repo_root.rglob("*") if p.is_file()
        ]

    for rel_path in candidates:
        if _should_ignore(rel_path, ignore_patterns):
            continue
        full_path_raw = repo_root / rel_path
        full_path = full_path_raw.resolve()
        if not full_path.is_relative_to(repo_root.resolve()):
            continue
        if not full_path.is_file():
            continue
        if full_path_raw.is_symlink() or full_path.is_symlink():
            continue
        if parser.detect_language(full_path) is None:
            continue
        if _is_binary(full_path):
            continue
        files.append(rel_path)

    return files


def find_dependents(store: GraphStore, file_path: str) -> list[str]:
    """Find files that import from or depend on the given file.

    Looks at IMPORTS_FROM edges where target matches the file path.
    """
    dependents = set()
    # Find edges where someone imports from this file
    edges = store.get_edges_by_target(file_path, kind="IMPORTS_FROM")
    for e in edges:
        # The source is a file path (for IMPORTS_FROM edges)
        dependents.add(e.file_path)

    # Also check for DEPENDS_ON edges
    nodes = store.get_nodes_by_file(file_path)
    qns = [n.qualified_name for n in nodes]
    if qns:
        batch_edges = store.get_edges_by_targets(
            qns, kind=("CALLS", "IMPORTS_FROM", "INHERITS", "IMPLEMENTS")
        )
        for e in batch_edges:
            dependents.add(e.file_path)

    dependents.discard(file_path)
    return list(dependents)


def full_build(repo_root: Path, store: GraphStore) -> dict:
    """Full rebuild of the entire graph."""
    parser = CodeParser()
    files = collect_all_files(repo_root)

    # Purge stale data from files no longer on disk
    existing_files = set(store.get_all_files())
    current_abs = {str(repo_root / f) for f in files}
    for stale in existing_files - current_abs:
        store.remove_file_data(stale)

    total_nodes = 0
    total_edges = 0
    errors = []
    file_count = len(files)

    for i, rel_path in enumerate(files, 1):
        full_path = (repo_root / rel_path).resolve()
        if not full_path.is_relative_to(repo_root.resolve()):
            continue
        try:
            n_nodes, n_edges = _update_single_file(full_path, parser, store)
            total_nodes += n_nodes
            total_edges += n_edges
        except (OSError, PermissionError) as e:
            errors.append({"file": rel_path, "error": str(e)})
        except Exception as e:
            logger.warning("Error parsing %s: %s", rel_path, e)
            errors.append({"file": rel_path, "error": str(e)})
        if i % 50 == 0 or i == file_count:
            logger.info("Progress: %d/%d files parsed", i, file_count)

    store.set_metadata("last_updated", time.strftime("%Y-%m-%dT%H:%M:%S"))
    store.set_metadata("last_build_type", "full")
    current_head = get_head_sha(repo_root)
    if current_head:
        store.set_metadata("last_built_head", current_head)
    store.commit()

    return {
        "files_parsed": len(files),
        "total_nodes": total_nodes,
        "total_edges": total_edges,
        "errors": errors,
    }


def _get_effective_base_and_changed_files(
    repo_root: Path,
    store: GraphStore,
    base: str,
    changed_files: list[str] | None,
) -> tuple[str, list[str]]:
    """Widen default base and determine changed files."""
    effective_base = base
    if changed_files is None and base == "HEAD~1":
        last_head = store.get_metadata("last_built_head")
        if last_head and is_valid_commit(repo_root, last_head):
            current_head = get_head_sha(repo_root)
            if current_head and current_head != last_head:
                effective_base = last_head

    if changed_files is None:
        changed_files = get_changed_files(repo_root, effective_base)

    return effective_base, changed_files


def _get_dependent_files(
    repo_root: Path,
    store: GraphStore,
    changed_files: list[str],
) -> set[str]:
    """Find dependent files (files that import from changed files)."""
    dependent_files: set[str] = set()
    repo_resolved = repo_root.resolve()
    for rel_path in changed_files:
        full_path_raw = repo_root / rel_path
        full_path = full_path_raw.resolve()
        if not full_path.is_relative_to(repo_resolved):
            continue
        if full_path_raw.is_symlink() or full_path.is_symlink():
            continue

        deps = find_dependents(store, str(full_path))
        for d in deps:
            try:
                dependent_files.add(str(Path(d).relative_to(repo_root)))
            except ValueError:
                dependent_files.add(d)
    return dependent_files


def _snapshot_pre_functions(
    repo_root: Path,
    store: GraphStore,
    all_files: set[str],
) -> dict[str, dict[str, str]]:
    """Create per-file snapshot of pre-update Function qualified_names.

    Uses a single batched query over just the needed columns, so reading
    hashes does not cost N+1 database calls or materialize full GraphNode
    objects (including large source_text fields).
    """
    pre_functions: dict[str, dict[str, str]] = {}
    repo_resolved = repo_root.resolve()
    valid_abs_paths = []
    abs_to_rel = {}

    for rel_path in all_files:
        pre_functions[rel_path] = {}
        abs_pre = (repo_root / rel_path).resolve()
        if not abs_pre.is_relative_to(repo_resolved):
            continue
        abs_str = str(abs_pre)
        valid_abs_paths.append(abs_str)
        abs_to_rel[abs_str] = rel_path

    if not valid_abs_paths:
        return pre_functions

    # Batch query for all needed files, fetching only the required columns
    results = store.get_function_hashes_by_files(valid_abs_paths)

    for row in results:
        rel_path = abs_to_rel[row["file_path"]]
        pre_functions[rel_path][row["qualified_name"]] = row["file_hash"] or ""

    return pre_functions


def _update_files_in_store(
    repo_root: Path,
    store: GraphStore,
    parser: CodeParser,
    all_files: set[str],
    ignore_patterns: list[str],
) -> tuple[int, int, set[str], list[dict[str, Any]]]:
    """Process file updates (deletions and re-parsing)."""
    total_nodes = 0
    total_edges = 0
    actually_updated: set[str] = set()
    errors = []
    repo_resolved = repo_root.resolve()

    for rel_path in all_files:
        if _should_ignore(rel_path, ignore_patterns):
            continue
        abs_path_raw = repo_root / rel_path
        abs_path = abs_path_raw.resolve()
        if not abs_path.is_relative_to(repo_resolved):
            continue
        if not abs_path.is_file():
            store.remove_file_data(str(abs_path))
            actually_updated.add(rel_path)
            continue
        if abs_path_raw.is_symlink() or abs_path.is_symlink():
            continue
        if parser.detect_language(abs_path) is None:
            continue

        try:
            source_preview = abs_path.read_bytes()
            fhash = hashlib.sha256(source_preview).hexdigest()

            # Check file_hash directly via SQL to avoid materializing all
            # GraphNode objects for unchanged files.
            existing_hash = store.get_file_hash(str(abs_path))
            if existing_hash == fhash:
                continue

            n_nodes, n_edges = _update_single_file(
                abs_path, parser, store, source=source_preview, fhash=fhash
            )
            total_nodes += n_nodes
            total_edges += n_edges
            actually_updated.add(rel_path)
        except (OSError, PermissionError) as e:
            errors.append({"file": rel_path, "error": str(e)})
        except Exception as e:
            logger.warning("Error parsing %s: %s", rel_path, e)
            errors.append({"file": rel_path, "error": str(e)})

    return total_nodes, total_edges, actually_updated, errors


def _finalize_incremental_metadata(
    repo_root: Path,
    store: GraphStore,
    repo_registry: RepoRegistry | None = None,
) -> None:
    """Update store metadata and commit changes.

    When ``repo_registry`` is provided and ``repo_root`` is a git
    repo, the registry's ``last_indexed_sha`` for the matching
    ``repo_id`` is bumped to the current HEAD. Non-git directories and
    callers who don't pass a registry skip the SHA refresh silently —
    federation works without git.
    """
    store.set_metadata("last_updated", time.strftime("%Y-%m-%dT%H:%M:%S"))
    store.set_metadata("last_build_type", "incremental")
    current_head = get_head_sha(repo_root)
    if current_head:
        store.set_metadata("last_built_head", current_head)
        if repo_registry is not None:
            try:
                repo_id = repo_registry.assign(repo_root)
            except ValueError:
                # Repo not registered — nothing to update. The caller
                # is responsible for ``registry.add(repo_root)`` before
                # incremental_update if they want SHA tracking.
                repo_id = None
            if repo_id is not None:
                repo_registry.update_last_indexed_sha(repo_id, current_head)
    store.commit()


def incremental_update(
    repo_root: Path,
    store: GraphStore,
    base: str = "HEAD~1",
    changed_files: list[str] | None = None,
    *,
    repo_registry: RepoRegistry | None = None,
) -> dict:
    """Incremental update: re-parse changed + dependent files only.

    Parameters
    ----------
    repo_registry:
        Phase 2 Task 9 — when provided, the registry's
        ``last_indexed_sha`` for the repo matching ``repo_root`` is
        bumped to the current ``HEAD`` once indexing completes. The
        registry is currently only used for the SHA refresh; per-node
        federation tagging on the parser path is handled by
        ``CodeParser.parse_file`` callers (Task 10 wires this into the
        full build).
    """
    parser = CodeParser()
    ignore_patterns = _load_ignore_patterns(repo_root)

    # 1. Determine changed files
    effective_base, changed_files = _get_effective_base_and_changed_files(
        repo_root, store, base, changed_files
    )

    if not changed_files:
        # Even on a no-op pass, refresh ``last_indexed_sha`` so a
        # registry that's just been bootstrapped reflects HEAD instead
        # of staying stuck on ``None``.
        if repo_registry is not None:
            head = get_head_sha(repo_root)
            if head:
                try:
                    rid = repo_registry.assign(repo_root)
                except ValueError:
                    rid = None
                if rid is not None:
                    repo_registry.update_last_indexed_sha(rid, head)
        return {
            "files_updated": 0,
            "total_nodes": 0,
            "total_edges": 0,
            "changed_files": [],
            "dependent_files": [],
        }

    # 2. Find dependent files
    dependent_files = _get_dependent_files(repo_root, store, changed_files)
    all_files = set(changed_files) | dependent_files

    # 3. Snapshot pre-update functions
    pre_functions = _snapshot_pre_functions(repo_root, store, all_files)

    # 4. Process updates
    total_nodes, total_edges, actually_updated, errors = _update_files_in_store(
        repo_root, store, parser, all_files, ignore_patterns
    )

    # 5. Build reviewer summary
    reviewer_summary = _build_reviewer_summary(
        store=store,
        repo_root=repo_root,
        pre_functions=pre_functions,
        changed_files=list(changed_files),
        actually_updated=actually_updated,
    )

    # 6. Finalize metadata and commit
    _finalize_incremental_metadata(repo_root, store, repo_registry=repo_registry)

    return {
        "files_updated": len(all_files),
        "total_nodes": total_nodes,
        "total_edges": total_edges,
        "changed_files": list(changed_files),
        "dependent_files": list(dependent_files),
        "errors": errors,
        "reviewer_summary": reviewer_summary,
    }


def _build_reviewer_summary(
    store: GraphStore,
    repo_root: Path,
    pre_functions: dict[str, dict[str, str]],
    changed_files: list[str],
    actually_updated: set[str],
) -> dict:
    """Diff pre/post Function nodes for the #329 reviewer summary.

    Treats the explicitly-changed files as the "source of change":
    a function disappearing from one of those files is ``removed``,
    a new function appearing is ``added``, and a function whose
    qualified_name persists across the change is ``modified``.
    Dependent files are not analyzed here (their diffs are noise from
    the reviewer's perspective -- they only re-parsed because their
    callee surface shifted).

    ``modules_newly_impacted`` lists files that were re-parsed but
    were not in the user's ``changed_files`` set -- i.e. dependent
    files pulled in by import / call edges.
    """
    changed_set = set(changed_files)
    functions_added: list[str] = []
    functions_removed: list[str] = []
    functions_modified: list[str] = []
    repo_resolved = repo_root.resolve()

    for rel_path in changed_set:
        if rel_path not in actually_updated:
            continue
        abs_path = (repo_root / rel_path).resolve()
        if not abs_path.is_relative_to(repo_resolved):
            continue
        post_nodes = store.get_nodes_by_file(str(abs_path))
        post_qns = {n.qualified_name for n in post_nodes if n.kind == "Function"}
        pre_qns = set(pre_functions.get(rel_path, {}).keys())

        functions_added.extend(sorted(post_qns - pre_qns))
        functions_removed.extend(sorted(pre_qns - post_qns))
        # "Modified" = present in both AND file was actually updated this run.
        # We don't have per-function content hashes, so file-level hash change
        # plus persistent qualified_name is our best signal.
        functions_modified.extend(sorted(post_qns & pre_qns))

    modules_newly_impacted = sorted(actually_updated - changed_set)

    return {
        "functions_added": functions_added,
        "functions_removed": functions_removed,
        "functions_modified": functions_modified,
        "modules_newly_impacted": modules_newly_impacted,
    }


def incremental_update_from_hook() -> None:
    """Entry point for PostToolUse hook -- replaces CLI 'update' subcommand."""
    repo_root = find_repo_root()
    if not repo_root:
        return
    db_path = get_db_path(repo_root)
    store = GraphStore(db_path)
    try:
        incremental_update(repo_root, store, base="HEAD~1")
    finally:
        store.close()


# ---------------------------------------------------------------------------
# Watch mode
# ---------------------------------------------------------------------------


_DEBOUNCE_SECONDS = 0.3


def _update_single_file(
    abs_path: Path,
    parser: CodeParser,
    store: GraphStore,
    source: bytes | None = None,
    fhash: str | None = None,
) -> tuple[int, int]:
    """Internal helper to parse and store a single file's data.

    Returns (node_count, edge_count).
    """
    if source is None:
        source = abs_path.read_bytes()
    if fhash is None:
        import hashlib

        fhash = hashlib.sha256(source).hexdigest()
    nodes, edges = parser.parse_bytes(abs_path, source)
    store.store_file_nodes_edges(str(abs_path), nodes, edges, fhash)
    return len(nodes), len(edges)


class GraphUpdateHandler(FileSystemEventHandler):
    """Handles file system events for the watch mode."""

    def __init__(
        self,
        repo_root: Path,
        store: GraphStore,
        parser: CodeParser,
        ignore_patterns: list[str],
    ):
        self.repo_root = repo_root
        self.store = store
        self.parser = parser
        self.ignore_patterns = ignore_patterns
        self._pending: set[str] = set()
        self._lock = threading.Lock()
        self._timer: threading.Timer | None = None

    def _should_handle(self, path: str) -> bool:
        if Path(path).is_symlink():
            return False
        try:
            rel = str(Path(path).relative_to(self.repo_root))
        except ValueError:
            return False
        if _should_ignore(rel, self.ignore_patterns):
            return False
        if self.parser.detect_language(Path(path)) is None:
            return False
        return True

    def on_modified(self, event):
        if event.is_directory:
            return
        if self._should_handle(event.src_path):
            self._schedule(event.src_path)

    def on_created(self, event):
        if event.is_directory:
            return
        if self._should_handle(event.src_path):
            self._schedule(event.src_path)

    def on_deleted(self, event):
        if event.is_directory:
            return
        # Only handle files we would normally track
        try:
            rel = str(Path(event.src_path).relative_to(self.repo_root))
        except ValueError:
            return
        if _should_ignore(rel, self.ignore_patterns):
            return
        self.store.remove_file_data(event.src_path)
        self.store.commit()
        logger.info("Removed: %s", rel)

    def _schedule(self, abs_path: str):
        """Add file to pending set and reset the debounce timer."""
        with self._lock:
            self._pending.add(abs_path)
            if self._timer is not None:
                self._timer.cancel()
            self._timer = threading.Timer(_DEBOUNCE_SECONDS, self._flush)
            self._timer.start()

    def _flush(self):
        """Process all pending files after the debounce window."""
        with self._lock:
            paths = list(self._pending)
            self._pending.clear()
            self._timer = None

        for abs_path in paths:
            self._update_file(abs_path)

    def _update_file(self, abs_path: str):
        path = Path(abs_path)
        if not path.is_file():
            return
        if path.is_symlink():
            return
        if _is_binary(path):
            return
        try:
            n_nodes, n_edges = _update_single_file(path, self.parser, self.store)
            self.store.set_metadata("last_updated", time.strftime("%Y-%m-%dT%H:%M:%S"))
            self.store.commit()
            rel = str(path.relative_to(self.repo_root))
            logger.info("Updated: %s (%d nodes, %d edges)", rel, n_nodes, n_edges)
        except Exception as e:
            logger.error("Error updating %s: %s", abs_path, e)


def watch(repo_root: Path, store: GraphStore) -> None:
    """Watch for file changes and auto-update the graph.

    Uses a 300ms debounce to batch rapid-fire saves into a single update.
    """
    parser = CodeParser()
    ignore_patterns = _load_ignore_patterns(repo_root)

    handler = GraphUpdateHandler(repo_root, store, parser, ignore_patterns)
    observer = Observer()
    observer.schedule(handler, str(repo_root), recursive=True)
    observer.start()

    logger.info("Watching %s for changes... (Ctrl+C to stop)", repo_root)
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()
    logger.info("Watch stopped.")
